mutation CreateArticle($input: CreateArticleInput!) {
  createArticle(input: $input)
}

mutation UpdateArticle($input: UpdateArticleInput!) {
  updateArticle(input: $input)
}

mutation DeleteArticle($input: IdInput!) {
  deleteArticle(input: $input)
}

query Article($id: String!) {
  article(id: $id) {
    author {
      id
      name
      avatar {
        url
      }
    }
    content
    createTime
    id
    title
    updateTime
  }
}

query ArticleList($filter: ArticleListInput, $limit: Int, $offset: Int) {
  articleList(filter: $filter, limit: $limit, offset: $offset) {
    author {
      name
    }
    cover {
      name
      url
    }
    createTime
    id
    summary
    tags {
      name
    }
    title
    updateTime
  }
}

query TagList($filter: TagListInput, $limit: Int, $offset: Int) {
  tagList(filter: $filter, limit: $limit, offset: $offset) {
    id
    name
    type
  }
}

query Tag($filter: TagInput!) {
  tag(filter: $filter) {
    id
    name
    type
  }
}
