fragment BaseUser on User {
  id
  avatar {
    name
    url
  }
  name
  signature
}

query Me {
  me {
    ...BaseUser
  }
}

query User($id: String!) {
  user(id: $id) {
    ...BaseUser
  }
}

query UserList($filter: SearchInput, $limit: Int, $offset: Int) {
  userList(filter: $filter, limit: $limit, offset: $offset) {
    ...BaseUser
  }
}

query MyFollowedUserList($filter: SearchInput, $limit: Int, $offset: Int) {
  myFollowedUserList(filter: $filter, limit: $limit, offset: $offset) {
    ...BaseUser
  }
}

mutation FollowUser($input: IdInput!) {
  followUser(input: $input)
}

mutation UnFollowUser($input: IdInput!) {
  unFollowUser(input: $input)
}

query IsFollowedUser($filter: IdInput!) {
  isFollowedUser(filter: $filter)
}
